routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// welcome route
Route::get('/', function () {
    return view('welcome');
});

// Auth route
Auth::routes();

// Main routes
Route::get('/home', 'HomeController@index')->name('home');

// Admin Routes
Route::group(['prefix' => 'admin','middleware' => 'App\Http\Middleware\AdminMiddleware','as'=>'admin.'], function()
{
    // View and Controller routes
    Route::get('manage-candidate', 'admin\AdminController@manage_candidate')->name('manage.candidate');
    Route::get('add-candidate', 'admin\AdminController@show_add_candiddate')->name('add.candidate');
    Route::get('candidate/{id}/edit', 'admin\AdminController@show_edit_candiddate')->name('edit.candidate');
    Route::post('store-candidate', 'admin\AdminController@store_candiddate')->name('store.candidate');
    Route::post('update-candidate', 'admin\AdminController@update_candiddate')->name('update.candidate');
    Route::get('candidate/{id}/delete', 'admin\AdminController@delete_candiddate')->name('delete.candidate');
    Route::get('candidate/{id}/view', 'admin\AdminController@show_candiddate')->name('show.candidate');
    
    //Data Table Ajax routes
    Route::get('get-candidate', 'admin\AdminAjaxController@get_candidates')->name('get.candidate');




});
// Candidates Routes
Route::group(['prefix' => 'candidate','middleware' => 'App\Http\Middleware\CandidateMiddleware','as'=>'candidate.'], function()
{
    Route::get('profile', 'candidate\CandidateController@show_candiddate')->name('profile');
});

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    @if (auth()->user()->role==2)

                     <span class="title"> Wellcome {{auth()->user()->first_name}} {{auth()->user()->last_name}} </span>

                      <div class="links">
                        <a href="{{ route('admin.manage.candidate') }}" class="btn btn-info">Manage Candidate</a>
                        
                     </div>

                     @else(auth()->user()->role==1) 

                     <span class="title">   Wellcome {{auth()->user()->first_name}} {{auth()->user()->last_name}}</span>
                     <div class="links">
                            <a href="{{ route('candidate.profile') }}" class="btn btn-info">My Profile</a>
                            
                         </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/unauthorized.blade.php
<!DOCTYPE html>
<html lang="id" dir="ltr">

<head>
     <meta charset="utf-8" />
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
     <meta name="description" content="" />
     <meta name="author" content="" />

     <!-- Title -->
     <title>Sorry, This Page Can&#39;t Be Accessed</title>
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" />
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous" />
</head>

<body class="bg-dark text-white py-5">
     <div class="container py-5">
          <div class="row">
               <div class="col-md-2 text-center">
                    <p><i class="fa fa-exclamation-triangle fa-5x"></i><br/>Status Code: 403</p>
               </div>
               <div class="col-md-10">
                    <h3>OPPSSS!!!! Sorry...</h3>
                    <p>Sorry, your access is refused due to security reasons of our server and also our sensitive data.<br/>Please go back to the previous page to continue browsing.</p>
                    <a class="btn btn-danger" href="javascript:history.back()">Go Back</a>
               </div>
          </div>
     </div>
</body>

</html>