routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// welcome route
Route::get('/', function () {
    return view('welcome');
});

// Auth route
Auth::routes();

// Main routes
Route::get('/home', 'HomeController@index')->name('home');

// Admin Routes
Route::group(['prefix' => 'admin','middleware' => 'App\Http\Middleware\AdminMiddleware','as'=>'admin.'], function()
{
    // View and Controller routes
    Route::get('manage-candidate', 'admin\AdminController@manage_candidate')->name('manage.candidate');
    Route::get('add-candidate', 'admin\AdminController@show_add_candiddate')->name('add.candidate');
    Route::get('candidate/{id}/edit', 'admin\AdminController@show_edit_candiddate')->name('edit.candidate');
    Route::post('store-candidate', 'admin\AdminController@store_candiddate')->name('store.candidate');
    Route::post('update-candidate', 'admin\AdminController@update_candiddate')->name('update.candidate');
    Route::get('candidate/{id}/delete', 'admin\AdminController@delete_candiddate')->name('delete.candidate');
    Route::get('candidate/{id}/view', 'admin\AdminController@show_candiddate')->name('show.candidate');
    
    //Data Table Ajax routes
    Route::get('get-candidate', 'admin\AdminAjaxController@get_candidates')->name('get.candidate');




});
// Candidates Routes
Route::group(['prefix' => 'candidate','middleware' => 'App\Http\Middleware\CandidateMiddleware','as'=>'candidate.'], function()
{
    Route::get('profile', 'candidate\CandidateController@show_candiddate')->name('profile');
});

resources/views/admin/add-candidate.blade.php
@extends('layouts.app')


@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Add Candidate <a href="{{ route('admin.manage.candidate') }}" class="btn btn-success float-sm-right">List All Candidates</a> </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <form method="POST" action="{{ route('admin.store.candidate') }}" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group row">
                            <label for="first_name" class="col-md-4 col-form-label text-md-right">{{ __('First Name') }}</label>

                            <div class="col-md-6">
                                <input id="first_name" type="text" class="form-control @error('first_name') is-invalid @enderror" name="first_name" value="{{ old('first_name') }}" required autocomplete="first_name" autofocus>

                                @error('first_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="last_name" class="col-md-4 col-form-label text-md-right">{{ __('Last Name') }}</label>

                            <div class="col-md-6">
                                <input id="last_name" type="text" class="form-control @error('last_name') is-invalid @enderror" name="last_name" value="{{ old('last_name') }}" required autocomplete="last_name" autofocus>

                                @error('last_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>


                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required>

                                @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="cv_file" class="col-md-4 col-form-label text-md-right">{{ __('Skills') }}</label>

                            <div class="col-md-6">
                                <select class="skills form-control" name="skills[]"  multiple>
                                        <option disabled>Select Skills</option>
                                    @foreach($skills as $skill)
                                        <option value="{{ $skill->name }}">{{ $skill->name }}</option>
                                    @endforeach
                                  </select>
                            </div>
                            @error('skills')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                        </div>

                       

                        <div class="form-group row">
                            <label for="cv_file" class="col-md-4 col-form-label text-md-right">{{ __('Upload CV') }}</label>

                            <div class="col-md-6">
                                <input id="cv_file" type="file" class="form-control" name="cv_file" accept=
                                "application/msword, application/pdf">
                            </div>
                            @error('cv_file')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Add Candidate') }}
                                </button>
                            </div>
                        </div>
                    </form>
                   
                   

                </div>
            </div>
        </div>
    </div>
</div>

@endsection
@section('page-script')
@stop

resources/views/admin/edit-candidate.blade.php
@extends('layouts.app')


@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit Candidate : <b>{{ $candidate->first_name.' '.$candidate->last_name }}</b> <a href="{{ route('admin.manage.candidate') }}" class="btn btn-success float-sm-right">List All Candidates</a> </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <form method="POST" action="{{ route('admin.update.candidate') }}" enctype="multipart/form-data">
                        @csrf
                         <input type="hidden" name="id" value="{{ $candidate->id }}">

                        <div class="form-group row">
                            <label for="first_name" class="col-md-4 col-form-label text-md-right">{{ __('First Name') }}</label>

                            <div class="col-md-6">
                                <input id="first_name" type="text" class="form-control @error('first_name') is-invalid @enderror" name="first_name" value="{{ $candidate->first_name }}" required autocomplete="first_name" autofocus>

                                @error('first_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="last_name" class="col-md-4 col-form-label text-md-right">{{ __('Last Name') }}</label>

                            <div class="col-md-6">
                                <input id="last_name" type="text" class="form-control @error('last_name') is-invalid @enderror" name="last_name" value="{{ $candidate->last_name }}" required autocomplete="last_name" autofocus>

                                @error('last_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>


                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $candidate->email }}" required autocomplete="email">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password">

                                @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="cv_file" class="col-md-4 col-form-label text-md-right">{{ __('Skills') }}</label>

                            <div class="col-md-6">
                               
                                @if($candidate->skills)
                                @php
                                $c_skills = explode(', ', $candidate->skills);
                                @endphp
                                <select class="skills form-control" name="skills[]"  multiple>
                                        <option disabled>Select Skills</option>
                                        
                                    @foreach($skills as $skill)
                                        <option value="{{ $skill->name }}" <?= (in_array($skill->name, $c_skills) ? 'selected' : '') ?>>{{ $skill->name }}</option>
                                    @endforeach
                                  </select>
                                  @else
                                  <select class="skills form-control" name="skills[]"  multiple>
                                        <option selected disabled>Select Skills</option>
                                        
                                    @foreach($skills as $skill)
                                        <option value="{{ $skill->name }}">{{ $skill->name }}</option>
                                    @endforeach
                                  </select>
                                  @endif
                            </div>
                            @error('skills')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                        </div>

                       

                        <div class="form-group row">
                            <label for="cv_file" class="col-md-4 col-form-label text-md-right">{{ __('Upload CV') }}</label>

                            <div class="col-md-6">
                                <input id="cv_file" type="file" class="form-control" name="cv_file" accept=
                                "application/msword, application/pdf">
                            </div>
                            @error('cv_file')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                            @if($candidate->cv_file)
                            <div class="col-md-6 offset-md-4">
                            <br/>
                            <b>Resume: <a href="{{asset('cv_files').'/'.$candidate->cv_file }}">Download Resume</a></b>
                            </div>
                            @else
                            <div class="col-md-6 offset-md-4">
                                    <br/>
                                    <b>No resume uploaded by candidate</b>
                                    </div>
                            @endif
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Update Candidate') }}
                                </button>
                            </div>
                        </div>
                    </form>
                   
                   

                </div>
            </div>
        </div>
    </div>
</div>

@endsection
@section('page-script')

@stop

resources/views/admin/manage-candidate.blade.php
@extends('layouts.app')


@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Manage Candidate <a href="{{ route('admin.add.candidate') }}" class="btn btn-success float-sm-right">Add Candidate</a> </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <input type="text" name="skills" class="form-control searchSkills" placeholder="Search for skills Only...">
                    <br>
                    <br>
                   
                    <table id="users" class="table table-hover table-condensed" style="width:100%">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>Email</th>
                                <th>Skills</th>
                                <th>Resume</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>

@endsection
@section('page-script')
<script type="text/javascript">
    jQuery(function () {
        $.ajaxSetup({
            headers: {
              'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
          });
      
      var table = jQuery('#users').DataTable({
          processing: true,
          serverSide: true,
         // ajax: "{{ route('admin.get.candidate') }}",
          ajax: {
            url: "{{ route('admin.get.candidate') }}",
            data: function (d) {
                  d.s_skills = $('.searchSkills').val(),
                  d.search = $('input[type="search"]').val()
              }
          },
          columns: [
              {data: 'DT_RowIndex', name: 'DT_RowIndex'},
              {data: 'first_name', name: 'first_name'},
              {data: 'last_name', name: 'last_name'},
              {data: 'email', name: 'email'},
              {data: 'skills', name: 'skills'},
              {data: 'cv_status', name: 'cv_status'},
              {data: 'action', name: 'action', orderable: false, searchable: false},
          ]
      });
     
      $(".searchSkills").keyup(function(){
            table.draw();
        });
    });
  </script>
  @stop




{{--  {data: 'action', name: 'action', orderable: false, searchable: false},  --}}

resources/views/admin/show-candidate.blade.php
@extends('layouts.app')


@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Candidate Details : <b>{{ $candidate->first_name.' '.$candidate->last_name }}</b> <a href="{{ route('admin.manage.candidate') }}" class="btn btn-success float-sm-right">List All Candidates</a> </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    
                     
                        <div class="card-body">
                            <h4 class="card-title">{{ $candidate->first_name }} {{ $candidate->last_name }}</h4>
                            <p class="card-text"><b>Email:</b> {{ $candidate->email }}<br/>
                            <b>Resume: <a href="{{asset('cv_files').'/'.$candidate->cv_file }}">Download Resume</a></b>
                            </p>
                        </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection
@section('page-script')

@stop